SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS bordro_maliyet_ozetleri (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 bordro_id BIGINT UNSIGNED NOT NULL,
 toplam_kazanc DECIMAL(18,2) NOT NULL DEFAULT 0,
 ssk_prim_isveren DECIMAL(18,2) NOT NULL DEFAULT 0,
 issizlik_prim_isveren DECIMAL(18,2) NOT NULL DEFAULT 0,
 baz_toplam DECIMAL(18,2) NOT NULL DEFAULT 0,
 kar_orani DECIMAL(8,4) NOT NULL DEFAULT 4,
 kar_tutari DECIMAL(18,2) NOT NULL DEFAULT 0,
 genel_gider_orani DECIMAL(8,4) NOT NULL DEFAULT 7,
 genel_gider_tutari DECIMAL(18,2) NOT NULL DEFAULT 0,
 toplam_hakedis_tutari DECIMAL(18,2) NOT NULL DEFAULT 0,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_bordro_maliyet (bordro_id),
 CONSTRAINT fk_bmo_bordro FOREIGN KEY (bordro_id) REFERENCES bordrolar(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;
